import { createContext, useContext, useState } from 'react';

const T = {
  en: {
    appName: 'Ethiopian Electric Utility', appSub: 'Service Management System',
    tagline: 'Reliable Power for Every Ethiopian',
    login: 'Login', register: 'Register', logout: 'Logout',
    email: 'Email', password: 'Password', fullName: 'Full Name', phone: 'Phone',
    role: 'Role', serviceId: 'EEU Service ID', createAccount: 'Create Account',
    loggingIn: 'Logging in...', creatingAccount: 'Creating account...',
    accountCreated: 'Account created! You can now login.',
    loginFailed: 'Login failed', registerFailed: 'Registration failed',
    citizen: 'Citizen', approver: 'Approver', electrician: 'Electrician', admin: 'Admin',
    dashboard: 'Dashboard', overview: 'Overview', language: 'Language',
    submitRequest: 'Submit Request', myRequests: 'My Requests',
    reportProblem: 'Report Problem', myReports: 'My Reports',
    title: 'Title', description: 'Description', location: 'Location',
    category: 'Category', submit: 'Submit', cancel: 'Cancel', confirm: 'Confirm',
    edit: 'Edit', delete: 'Delete', save: 'Save Changes', create: 'Create',
    pending: 'Pending', approved: 'Approved', rejected: 'Rejected',
    assigned: 'Assigned', completed: 'Completed', open: 'Open', resolved: 'Resolved',
    approve: 'Approve', reject: 'Reject', assignGroup: 'Assign Group',
    assignTeam: 'Assign Team', markComplete: 'Mark Complete',
    requestSubmitted: 'Request submitted successfully!',
    reportSubmitted: 'Report submitted successfully!',
    requestApproved: 'Request approved!', requestRejected: 'Request rejected.',
    groupAssigned: 'Group assigned!', serviceCompleted: 'Service completed!',
    thankYou: 'Thank you for your feedback!',
    noRequests: 'No requests yet.', noReports: 'No reports yet.',
    noAssigned: 'No assigned requests.', noCompleted: 'No completed requests yet.',
    reviewRequest: 'Review Your Request', reviewReport: 'Review Your Report',
    confirmSubmit: 'Confirm & Submit', previewSubmit: 'Preview Before Submit',
    viewMyRequests: 'View My Requests', viewMyReports: 'View My Reports',
    submitAnother: 'Submit Another', reportAnother: 'Report Another',
    reference: 'Reference', status: 'Status', submittedAt: 'Submitted',
    pendingReview: 'Pending Review', rateService: 'Rate this service',
    yourRating: 'Your rating', optionalFeedback: 'Optional feedback...',
    submitRating: 'Submit Rating',
    scanQR: 'Scan QR Code', manualReport: 'Manual Report',
    assetIdentified: 'Asset Identified', assetCode: 'Asset Code',
    problemType: 'Problem Type', photoUrl: 'Photo URL (optional)',
    gpsDetect: 'GPS', detectingGps: 'Detecting...',
    noGps: 'No GPS location', noLocation: 'No location',
    systemOverview: 'System Overview', totalUsers: 'Total Users',
    serviceRequests: 'Service Requests', infraReports: 'Infrastructure Reports',
    infraAssets: 'Infrastructure Assets', pendingRequests: 'Pending Requests',
    openReports: 'Open Reports', damagedAssets: 'Damaged Assets',
    requestsByStatus: 'Requests by Status', usersByRole: 'Users by Role',
    requestsByCategory: 'Requests by Category', reportsByType: 'Reports by Type',
    requestsOverTime: 'Requests Over Last 6 Months',
    reportLocations: 'Infrastructure Report Locations', noGpsReports: 'No GPS-tagged reports yet',
    infraManagement: 'Infrastructure Assets', addAsset: 'Add New Asset',
    assetType: 'Type', markActive: 'Mark Active', markDamaged: 'Mark Damaged',
    underRepair: 'Under Repair', showQR: 'Show QR', hideQR: 'Hide QR', downloadQR: 'Download QR',
    allRequests: 'All Requests', pendingTab: 'Pending', approverDashboard: 'Approver Dashboard',
    quickActions: 'Quick Actions', reviewPending: 'Review Pending',
    requestsByCategory2: 'Requests by Category',
    electricianDashboard: 'Electrician Dashboard', myGroup: 'Group',
    noGroupWarning: 'You are not assigned to any group yet. Contact admin.',
    assignedWork: 'Assigned Work', latestAssigned: 'Latest Assigned',
    enterServiceId: "Enter citizen's EEU Service ID to verify:",
    systemUsers: 'System Users', createUser: 'Create User',
    searchUsers: 'Search by name, email, or service ID...',
    allRoles: 'All Roles', showing: 'Showing', of: 'of', users: 'users',
    noUsersFound: 'No users found', actions: 'Actions', joined: 'Joined',
    createNewUser: 'Create New User', editUser: 'Edit User',
    newPassword: 'New Password (leave blank to keep current)',
    electricianNote: 'Electrician will be assigned to a group by admin after creation.',
    saving: 'Saving...',
    electricianGroups: 'Electrician Groups', createGroup: 'Create Group',
    groupName: 'Group name', groupDesc: 'Description (optional)',
    manageMembers: 'Manage Members', noMembers: 'No members yet',
    currentMembers: 'Current Members', selectElectrician: 'Select electrician to add...',
    add: 'Add', remove: 'Remove',
    catPowerOutage: 'Power Outage', catBilling: 'Billing', catMeter: 'Meter',
    catConnection: 'Connection', catMaintenance: 'Maintenance', catOther: 'Other',
    allCategories: 'All Categories', allStatuses: 'All Statuses', clear: 'Clear',
    results: 'results', rejectionReason: 'Rejection reason...',
    confirmReject: 'Confirm', selectGroup: 'Select electrician group...',
    welcomeBack: 'Welcome',
  },
  am: {
    appName: 'የኢትዮጵያ ኤሌክትሪክ አገልግሎት', appSub: 'የአገልግሎት አስተዳደር ስርዓት',
    tagline: 'ለእያንዳንዱ ኢትዮጵያዊ አስተማማኝ ኃይል',
    login: 'ግባ', register: 'ተመዝገብ', logout: 'ውጣ',
    email: 'ኢሜይል', password: 'የይለፍ ቃል', fullName: 'ሙሉ ስም', phone: 'ስልክ',
    role: 'ሚና', serviceId: 'የEEU አገልግሎት መታወቂያ', createAccount: 'መለያ ፍጠር',
    loggingIn: 'በመግባት ላይ...', creatingAccount: 'መለያ በመፍጠር ላይ...',
    accountCreated: 'መለያ ተፈጥሯል! አሁን መግባት ይችላሉ።',
    loginFailed: 'መግባት አልተሳካም', registerFailed: 'ምዝገባ አልተሳካም',
    citizen: 'ዜጋ', approver: 'አጽዳቂ', electrician: 'ኤሌክትሪሺያን', admin: 'አስተዳዳሪ',
    dashboard: 'ዳሽቦርድ', overview: 'አጠቃላይ እይታ', language: 'ቋንቋ',
    submitRequest: 'ጥያቄ አስገባ', myRequests: 'ጥያቄዎቼ',
    reportProblem: 'ችግር ሪፖርት አድርግ', myReports: 'ሪፖርቶቼ',
    title: 'ርዕስ', description: 'መግለጫ', location: 'ቦታ',
    category: 'ምድብ', submit: 'አስገባ', cancel: 'ሰርዝ', confirm: 'አረጋግጥ',
    edit: 'አርትዕ', delete: 'ሰርዝ', save: 'ለውጦችን አስቀምጥ', create: 'ፍጠር',
    pending: 'በመጠባበቅ ላይ', approved: 'ጸድቋል', rejected: 'ተቀባይነት አላገኘም',
    assigned: 'ተመድቧል', completed: 'ተጠናቋል', open: 'ክፍት', resolved: 'ተፈትቷል',
    approve: 'አጽድቅ', reject: 'ውድቅ አድርግ', assignGroup: 'ቡድን ምደብ',
    assignTeam: 'ቡድን ምደብ', markComplete: 'ተጠናቋል ምልክት አድርግ',
    requestSubmitted: 'ጥያቄ በተሳካ ሁኔታ ቀርቧል!',
    reportSubmitted: 'ሪፖርት በተሳካ ሁኔታ ቀርቧል!',
    requestApproved: 'ጥያቄ ጸድቋል!', requestRejected: 'ጥያቄ ውድቅ ሆኗል።',
    groupAssigned: 'ቡድን ተመድቧል!', serviceCompleted: 'አገልግሎት ተጠናቋል!',
    thankYou: 'ለአስተያየትዎ እናመሰግናለን!',
    noRequests: 'እስካሁን ምንም ጥያቄ የለም።', noReports: 'እስካሁን ምንም ሪፖርት የለም።',
    noAssigned: 'የተመደቡ ጥያቄዎች የሉም።', noCompleted: 'የተጠናቀቁ ጥያቄዎች የሉም።',
    reviewRequest: 'ጥያቄዎን ይገምግሙ', reviewReport: 'ሪፖርትዎን ይገምግሙ',
    confirmSubmit: 'አረጋግጥ እና አስገባ', previewSubmit: 'ከማስገባትዎ በፊት ይገምግሙ',
    viewMyRequests: 'ጥያቄዎቼን ይመልከቱ', viewMyReports: 'ሪፖርቶቼን ይመልከቱ',
    submitAnother: 'ሌላ አስገባ', reportAnother: 'ሌላ ሪፖርት አድርግ',
    reference: 'ማጣቀሻ', status: 'ሁኔታ', submittedAt: 'የቀረበበት ጊዜ',
    pendingReview: 'ለግምገማ በመጠባበቅ ላይ', rateService: 'አገልግሎቱን ይገምግሙ',
    yourRating: 'የእርስዎ ደረጃ', optionalFeedback: 'አስተያየት (አማራጭ)...',
    submitRating: 'ደረጃ አስገባ',
    scanQR: 'QR ኮድ ቃኝ', manualReport: 'በእጅ ሪፖርት',
    assetIdentified: 'ንብረት ተለይቷል', assetCode: 'የንብረት ኮድ',
    problemType: 'የችግር አይነት', photoUrl: 'የፎቶ URL (አማራጭ)',
    gpsDetect: 'GPS', detectingGps: 'በማወቅ ላይ...',
    noGps: 'GPS ቦታ የለም', noLocation: 'ቦታ የለም',
    systemOverview: 'የስርዓት አጠቃላይ እይታ', totalUsers: 'ጠቅላላ ተጠቃሚዎች',
    serviceRequests: 'የአገልግሎት ጥያቄዎች', infraReports: 'የመሠረተ ልማት ሪፖርቶች',
    infraAssets: 'የመሠረተ ልማት ንብረቶች', pendingRequests: 'በመጠባበቅ ላይ ያሉ ጥያቄዎች',
    openReports: 'ክፍት ሪፖርቶች', damagedAssets: 'የተጎዱ ንብረቶች',
    requestsByStatus: 'ጥያቄዎች በሁኔታ', usersByRole: 'ተጠቃሚዎች በሚና',
    requestsByCategory: 'ጥያቄዎች በምድብ', reportsByType: 'ሪፖርቶች በአይነት',
    requestsOverTime: 'ጥያቄዎች ባለፉት 6 ወራት',
    reportLocations: 'የሪፖርት ቦታዎች', noGpsReports: 'GPS ያላቸው ሪፖርቶች የሉም',
    infraManagement: 'የመሠረተ ልማት ንብረቶች', addAsset: 'ንብረት ጨምር',
    assetType: 'አይነት', markActive: 'ንቁ ምልክት አድርግ', markDamaged: 'የተጎዳ ምልክት አድርግ',
    underRepair: 'በጥገና ላይ', showQR: 'QR አሳይ', hideQR: 'QR ደብቅ', downloadQR: 'QR አውርድ',
    allRequests: 'ሁሉም ጥያቄዎች', pendingTab: 'በመጠባበቅ ላይ', approverDashboard: 'አጽዳቂ ዳሽቦርድ',
    quickActions: 'ፈጣን ድርጊቶች', reviewPending: 'በመጠባበቅ ላይ ያሉ ይገምግሙ',
    requestsByCategory2: 'ጥያቄዎች በምድብ',
    electricianDashboard: 'ኤሌክትሪሺያን ዳሽቦርድ', myGroup: 'ቡድን',
    noGroupWarning: 'ወደ ምንም ቡድን አልተመደቡም። አስተዳዳሪን ያነጋግሩ።',
    assignedWork: 'የተመደቡ ስራዎች', latestAssigned: 'የቅርብ ጊዜ ምደባዎች',
    enterServiceId: 'ለማረጋገጥ የዜጋውን EEU አገልግሎት መታወቂያ ያስገቡ:',
    systemUsers: 'የስርዓት ተጠቃሚዎች', createUser: 'ተጠቃሚ ፍጠር',
    searchUsers: 'በስም፣ ኢሜይል ወይም አገልግሎት መታወቂያ ይፈልጉ...',
    allRoles: 'ሁሉም ሚናዎች', showing: 'እያሳየ', of: 'ከ', users: 'ተጠቃሚዎች',
    noUsersFound: 'ምንም ተጠቃሚ አልተገኘም', actions: 'ድርጊቶች', joined: 'የተቀላቀሉበት',
    createNewUser: 'አዲስ ተጠቃሚ ፍጠር', editUser: 'ተጠቃሚ አርትዕ',
    newPassword: 'አዲስ የይለፍ ቃል (ባዶ ከተወ አይቀየርም)',
    electricianNote: 'ኤሌክትሪሺያን ከተፈጠረ በኋላ አስተዳዳሪ ወደ ቡድን ይመድባቸዋል።',
    saving: 'በማስቀመጥ ላይ...',
    electricianGroups: 'የኤሌክትሪሺያን ቡድኖች', createGroup: 'ቡድን ፍጠር',
    groupName: 'የቡድን ስም', groupDesc: 'መግለጫ (አማራጭ)',
    manageMembers: 'አባላትን አስተዳድር', noMembers: 'እስካሁን አባላት የሉም',
    currentMembers: 'አሁን ያሉ አባላት', selectElectrician: 'ኤሌክትሪሺያን ምረጥ...',
    add: 'ጨምር', remove: 'አስወግድ',
    catPowerOutage: 'የኃይል መቆራረጥ', catBilling: 'ክፍያ', catMeter: 'ሜትር',
    catConnection: 'ግንኙነት', catMaintenance: 'ጥገና', catOther: 'ሌላ',
    allCategories: 'ሁሉም ምድቦች', allStatuses: 'ሁሉም ሁኔታዎች', clear: 'አጽዳ',
    results: 'ውጤቶች', rejectionReason: 'የውድቅ ምክንያት...',
    confirmReject: 'አረጋግጥ', selectGroup: 'የኤሌክትሪሺያን ቡድን ምረጥ...',
    welcomeBack: 'እንኳን ደህና መጡ',
  },
  or: {
    appName: 'Tajaajila Elektirikii Itoophiyaa', appSub: 'Sirna Bulchiinsa Tajaajilaa',
    tagline: 'Humna Amanamaa Itoophiyaa Hundaaf',
    login: 'Seeni', register: "Galmaa'i", logout: "Ba'i",
    email: 'Imeelii', password: 'Jecha Darbii', fullName: 'Maqaa Guutuu', phone: 'Bilbila',
    role: 'Gahee', serviceId: 'ID Tajaajila EEU', createAccount: 'Herrega Uumi',
    loggingIn: 'Seenaa jira...', creatingAccount: 'Herrega uumaa jira...',
    accountCreated: "Herreegi uumame! Amma seenuu dandeessa.",
    loginFailed: 'Seenuu hin danda\'amne', registerFailed: 'Galmeessuu hin danda\'amne',
    citizen: 'Lammii', approver: 'Raggaasisaa', electrician: 'Elektiriishiyaanii', admin: 'Bulchaa',
    dashboard: 'Daashboordii', overview: 'Cuunfaa', language: 'Afaan',
    submitRequest: 'Gaaffii Galchi', myRequests: 'Gaaffii Koo',
    reportProblem: 'Rakkoo Gabaasi', myReports: 'Gabaasii Koo',
    title: 'Mata Duree', description: 'Ibsa', location: 'Bakka',
    category: 'Gosa', submit: 'Galchi', cancel: 'Haquu', confirm: 'Mirkaneessi',
    edit: 'Gulaali', delete: 'Haquu', save: 'Jijjiirama Kuusi', create: 'Uumi',
    pending: 'Eegaa jira', approved: 'Raggaasifame', rejected: 'Diderame',
    assigned: 'Ramadame', completed: 'Xumurame', open: 'Banaa', resolved: 'Furameera',
    approve: 'Raggaasi', reject: 'Didi', assignGroup: 'Garee Ramadi',
    assignTeam: 'Garee Ramadi', markComplete: 'Xumurameera Mallattessi',
    requestSubmitted: "Gaaffiin milkaa'inaan galame!",
    reportSubmitted: "Gabaasiin milkaa'inaan galame!",
    requestApproved: 'Gaaffiin raggaasifame!', requestRejected: 'Gaaffiin diderame.',
    groupAssigned: 'Gareen ramadame!', serviceCompleted: 'Tajaajilli xumurame!',
    thankYou: 'Yaada keessaniif galatoomi!',
    noRequests: 'Gaaffii hin jiru.', noReports: 'Gabaasii hin jiru.',
    noAssigned: 'Gaaffii ramadame hin jiru.', noCompleted: 'Gaaffii xumurame hin jiru.',
    reviewRequest: 'Gaaffii Kee Ilaalii', reviewReport: 'Gabaasii Kee Ilaalii',
    confirmSubmit: 'Mirkaneessi fi Galchi', previewSubmit: 'Osoo hin galchin ilaalii',
    viewMyRequests: 'Gaaffii Koo Ilaali', viewMyReports: 'Gabaasii Koo Ilaali',
    submitAnother: 'Biraa Galchi', reportAnother: 'Biraa Gabaasi',
    reference: 'Lakkoofsa', status: 'Haala', submittedAt: 'Yeroo Galame',
    pendingReview: 'Ilaalamaa jira', rateService: 'Tajaajila madaali',
    yourRating: 'Madaallii kee', optionalFeedback: 'Yaada (dirqama miti)...',
    submitRating: 'Madaallii Galchi',
    scanQR: 'QR Koodii Dubbisi', manualReport: 'Gabaasa Harkaan',
    assetIdentified: 'Qabeenya Adda Bahe', assetCode: 'Koodii Qabeenya',
    problemType: 'Gosa Rakkoo', photoUrl: 'URL Suuraa (dirqama miti)',
    gpsDetect: 'GPS', detectingGps: 'Argamaa jira...',
    noGps: 'GPS hin jiru', noLocation: 'Bakka hin jiru',
    systemOverview: 'Cuunfaa Sirna', totalUsers: 'Fayyadamtoota Waliigalaa',
    serviceRequests: 'Gaaffii Tajaajilaa', infraReports: 'Gabaasa Misooma',
    infraAssets: 'Qabeenya Misooma', pendingRequests: 'Gaaffii Eegaa jiru',
    openReports: 'Gabaasa Banaa', damagedAssets: 'Qabeenya Miidhamee',
    requestsByStatus: 'Gaaffii Haala Irratti', usersByRole: 'Fayyadamtoota Gahee Irratti',
    requestsByCategory: 'Gaaffii Gosa Irratti', reportsByType: 'Gabaasa Gosa Irratti',
    requestsOverTime: 'Gaaffii Ji\'a 6 Darbe',
    reportLocations: 'Bakka Gabaasaa', noGpsReports: 'Gabaasa GPS qabu hin jiru',
    infraManagement: 'Qabeenya Misooma', addAsset: 'Qabeenya Dabaluu',
    assetType: 'Gosa', markActive: 'Hojjachaa jira Mallattessi', markDamaged: 'Miidhamee Mallattessi',
    underRepair: 'Suphaa jira', showQR: 'QR Agarsiisi', hideQR: 'QR Dhoksi', downloadQR: 'QR Buusi',
    allRequests: 'Gaaffii Hunda', pendingTab: 'Eegaa jira', approverDashboard: 'Daashboordii Raggaasisaa',
    quickActions: 'Tarkaanfii Ariifataa', reviewPending: 'Eegaa jiru Ilaalii',
    requestsByCategory2: 'Gaaffii Gosa Irratti',
    electricianDashboard: 'Daashboordii Elektiriishiyaanii', myGroup: 'Garee',
    noGroupWarning: 'Garee kamiyyuu hin ramadamne. Bulchaa qunnamaa.',
    assignedWork: 'Hojii Ramadame', latestAssigned: 'Ramadama Haaraa',
    enterServiceId: "Mirkaneessuuf ID Tajaajila EEU lammii galchi:",
    systemUsers: 'Fayyadamtoota Sirna', createUser: 'Fayyadamaa Uumi',
    searchUsers: 'Maqaa, imeelii ykn ID irratti barbaadi...',
    allRoles: 'Gahee Hunda', showing: 'Agarsiisaa', of: 'keessaa', users: 'fayyadamtoota',
    noUsersFound: 'Fayyadamaan hin argamne', actions: 'Tarkaanfii', joined: 'Galee',
    createNewUser: 'Fayyadamaa Haaraa Uumi', editUser: 'Fayyadamaa Gulaali',
    newPassword: 'Jecha Darbii Haaraa (duwwaa dhiisi jijjiiruu hin barbaadne)',
    electricianNote: 'Elektiriishiyaaniin erga uumamee booda bulchaan garee ramada.',
    saving: 'Kuusaa jira...',
    electricianGroups: 'Garee Elektiriishiyaanii', createGroup: 'Garee Uumi',
    groupName: 'Maqaa Garee', groupDesc: 'Ibsa (dirqama miti)',
    manageMembers: 'Miseensota Bulchi', noMembers: 'Miseensa hin jiru',
    currentMembers: 'Miseensota Ammaa', selectElectrician: 'Elektiriishiyaanii filadhu...',
    add: 'Dabaluu', remove: 'Haquu',
    catPowerOutage: 'Humni Dhaabate', catBilling: 'Kafaltii', catMeter: 'Meetira',
    catConnection: 'Walquunnamtii', catMaintenance: 'Suphaa', catOther: 'Biraa',
    allCategories: 'Gosa Hunda', allStatuses: 'Haala Hunda', clear: 'Haquu',
    results: 'bu\'aa', rejectionReason: 'Sababaa diduu...',
    confirmReject: 'Mirkaneessi', selectGroup: 'Garee elektiriishiyaanii filadhu...',
    welcomeBack: 'Baga nagaan dhufte',
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');
  const t = T[lang] || T.en;
  const changeLang = (l) => { setLang(l); localStorage.setItem('lang', l); };
  return (
    <LangContext.Provider value={{ lang, t, changeLang }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
